
  <div id="clock">Total Time: 00:00</div>
<div id="validationMessage" style="display: none; color: red;">Please enter a valid workout name, duration, and description.</div>
<h3>Current Workout: <span id="currentObject2"></span></h3>
<h3>Description: <span id="currentWorkoutDescription"></span></h3>

    <div id="noWorkoutsMessage"></div>

</section>

<section>
  <button id="startBtn"><i class="fas fa-play"></i></button>
<button id="stopBtn"><i class="fas fa-pause"></i></button></section>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
